#!/bin/bash
########################
# Installs prggmr to the php include path
########################
VERSION=$(php -r "if (version_compare(PHP_VERSION, '5.4.0') >= 0) { echo '1'; } else { echo '0'; }")
if [ $VERSION != '1' ];
then
    echo "prggmr requires at least PHP 5.4"
    echo "Found"
    which php
    php -v
    exit;
fi;
PHPPATH=$(php -r "echo get_include_path();") 
INSTALLPATH=""
BINPATH="/usr/bin"
for x in $(echo $PHPPATH | tr ":" "\n")
do
    if [ "$x" != "." ]; then
        INSTALL_PATH="$x"
        break
    fi
done
if [[ $INSTALL_PATH = "" ]]; then
    echo "Could not find your PHP include path";
    exit;
fi
if [ -d "$INSTALL_PATH/prggmr" ]; then
    rm -rf "$INSTALL_PATH/prggmr"
fi;
mkdir $INSTALL_PATH/prggmr
cp -Rf * "$INSTALL_PATH/prggmr"
if [ -f "$BINPATH/prggmr" ]; then
    rm "$BINPATH/prggmr"
fi;
echo "Installed prggmr to $INSTALL_PATH/prggmr"
echo "Installed executable to $BINPATH/prggmr"
ln -s "$INSTALL_PATH/prggmr/bin/prggmr" "$BINPATH"
prggmr -v
echo "Report bugs to https://github.com/prggmr/prggmr/issues"
echo "Running Unit Tests"
prggmr --test