#!/bin/bash
########################
# Installs prggmr to the php include path
########################
PHPPATH=$(php -r "echo get_include_path();") 
INSTALLPATH=""
BINPATH="/usr/bin"
echo ""
echo "======================================="
echo "This will replace your existing install"
echo "======================================="
echo ""
for x in $(echo $PHPPATH | tr ":" "\n")
do
    if [ "$x" != "." ]; then
        INSTALL_PATH="$x"
        break
    fi
done
if [[ $INSTALL_PATH = "" ]]; then
    echo "Could not find your PHP include path";
    exit;
fi
install="$INSTALL_PATH/prggmr"
rm -rf "$install"
echo "Installing prggmr to $install"
mkdir $install
cp -Rf * "$install"
rm "$BINPATH/prggmr"
echo "Installing the executable prggmr file"
ln -s "$install/bin/prggmr" "$BINPATH"
prggmr -v
echo "Installed"
echo "Have fun with prggmr"
echo "Report bugs to https://github.com/nwhitingx/prggmr/issues"
echo "====================================="
prggmr -h

